[versions]
compose = "1.0.5"
kotlin = "1.5.31"
gradlePlugin = "7.0.3"
ktlint = "10.2.0"
koin = "3.1.3"
material = "1.4.0"
junit = "4.1.2"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
